name: HMCTS Management Information ADF Self Hosted Integration Runtime Image
trigger:
  - master

pool:
  vmImage: 'windows-latest'

parameters:
  - name: pushImage
    displayName: Push Docker Image To ACR
    type: boolean
    default: false

variables:
  projectName: 'mi'
  applicationName: 'adf-integration-runtime'
  azureSubscriptionEndpoint: 'DTS-SHAREDSERVICES-PROD'
  azureContainerRegistry: 'sdshmctspublic.azurecr.io'
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}: 
    deployTarget: prod
  ${{ if not(eq(variables['Build.SourceBranchName'], 'master')) }}: 
    deployTarget: dev

stages:
  - stage: BuildAndPush
    jobs:
      - job: BuildAndPush
        steps:
            - task: AzureCLI@1
              displayName: "ACR Login"
              inputs:
                azureSubscription: $(azureSubscriptionEndpoint)
                scriptLocation: "inlineScript"
                inlineScript: |
                  az acr login --name sdshmctspublic
            - task: AzureCLI@1
              displayName: "ACR Login"
              inputs:
                azureSubscription: $(azureSubscriptionEndpoint)
                scriptLocation: "inlineScript"
                inlineScript: |
                  az acr repository delete --name sdshmctspublic --image mi/azure-functions:stg-cde49a8 --yes
            - task: AzureCLI@1
              displayName: "ACR Login"
              inputs:
                azureSubscription: $(azureSubscriptionEndpoint)
                scriptLocation: "inlineScript"
                inlineScript: |
                  az acr repository delete --name sdshmctspublic --image mi/azure-functions:stg-3d7b2f1 --yes
            - task: AzureCLI@1
              displayName: "ACR Login"
              inputs:
                azureSubscription: $(azureSubscriptionEndpoint)
                scriptLocation: "inlineScript"
                inlineScript: |
                  az acr repository delete --name sdshmctspublic --image mi/azure-functions:stg-710d541 --yes
            - task: AzureCLI@1
              displayName: "ACR Login"
              inputs:
                azureSubscription: $(azureSubscriptionEndpoint)
                scriptLocation: "inlineScript"
                inlineScript: |
                  az acr repository delete --name sdshmctspublic --image mi/azure-functions:stg-c9a594d --yes
            - task: AzureCLI@1
              displayName: "ACR Login"
              inputs:
                azureSubscription: $(azureSubscriptionEndpoint)
                scriptLocation: "inlineScript"
                inlineScript: |
                  az acr repository delete --name sdshmctspublic --image mi/azure-functions:stg-73c9410 --yes
            - task: AzureCLI@1
              displayName: "ACR Login"
              inputs:
                azureSubscription: $(azureSubscriptionEndpoint)
                scriptLocation: "inlineScript"
                inlineScript: |
                  az acr repository delete --name sdshmctspublic --image mi/azure-functions:stg-172803c --yes
            - task: AzureCLI@1
              displayName: "ACR Login"
              inputs:
                azureSubscription: $(azureSubscriptionEndpoint)
                scriptLocation: "inlineScript"
                inlineScript: |
                  az acr repository delete --name sdshmctspublic --image mi/azure-functions:stg-d301bb7 --yes
            - task: AzureCLI@1
              displayName: "ACR Login"
              inputs:
                azureSubscription: $(azureSubscriptionEndpoint)
                scriptLocation: "inlineScript"
                inlineScript: |
                  az acr repository delete --name sdshmctspublic --image mi/azure-functions:stg-56d19fa --yes