name: HMCTS Management Information ADF Self Hosted Integration Runtime Image
trigger:
  - master

pool:
  vmImage: 'windows-latest'

parameters:
  - name: pushImage
    displayName: Push Docker Image To ACR
    type: boolean
    default: false

variables:
  projectName: 'mi'
  applicationName: 'adf-integration-runtime'
  azureSubscriptionEndpoint: 'DTS-SHAREDSERVICES-PROD'
  azureContainerRegistry: 'sdshmctspublic.azurecr.io'
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}: 
    deployTarget: prod
  ${{ if not(eq(variables['Build.SourceBranchName'], 'master')) }}: 
    deployTarget: dev

stages:
  - stage: BuildAndPush
    jobs:
      - job: BuildAndPush
        steps:
            - task: AzureCLI@1
              displayName: "ACR Login"
              inputs:
                azureSubscription: $(azureSubscriptionEndpoint)
                scriptLocation: "inlineScript"
                inlineScript: |
                  az acr login --name sdshmctspublic
            - task: AzureCLI@1
              displayName: "ACR Login"
              inputs:
                azureSubscription: $(azureSubscriptionEndpoint)
                scriptLocation: "inlineScript"
                inlineScript: |
                  az acr repository delete --name sdshmctspublic --image mi/adf-integration-runtime:dev-09b63f3 --yes
            - task: AzureCLI@1
              displayName: "ACR Login"
              inputs:
                azureSubscription: $(azureSubscriptionEndpoint)
                scriptLocation: "inlineScript"
                inlineScript: |
                  az acr repository delete --name sdshmctspublic --image mi/adf-integration-runtime:prod-2d93cf8 --yes
            - task: AzureCLI@1
              displayName: "ACR Login"
              inputs:
                azureSubscription: $(azureSubscriptionEndpoint)
                scriptLocation: "inlineScript"
                inlineScript: |
                  az acr repository delete --name sdshmctspublic --image mi/adf-integration-runtime:dev-814f45b --yes
            - task: AzureCLI@1
              displayName: "ACR Login"
              inputs:
                azureSubscription: $(azureSubscriptionEndpoint)
                scriptLocation: "inlineScript"
                inlineScript: |
                  az acr repository delete --name sdshmctspublic --image mi/adf-integration-runtime:dev-3ee27d5 --yes
